public class CC_ProcessesedScheduleData {
  @AuraEnabled
  public String orgDest { get; set; }
  @AuraEnabled
  public String displayName { get; set; }
  @AuraEnabled
  public String displayCode { get; set; }
  @AuraEnabled
  public String displayNameSubLoc { get; set; }
  @AuraEnabled
  public String displayCodeSubLoc { get; set; }
  @AuraEnabled
  public String iconShown { get; set; }
  @AuraEnabled
  public String arrival { get; set; }
  @AuraEnabled
  public String departure { get; set; }
  @AuraEnabled
  public String vesselName { get; set; }
  @AuraEnabled
  public String voyageNumber { get; set; }
}
