public class CC_SoftshipRatingConstant {
  public static Integer INTEGER_NO_OFSCHEDULE = Integer.valueOf(
    System.label.CC_SS_INTEGER_NO_OFSCHEDULE
  );
  public static Integer MAX_ROUTE = Integer.valueOf(
    System.label.CC_SS_MAX_ROUTE
  );
  public static Integer MAX_TRANSSHIPMENT = Integer.valueOf(
    System.label.CC_SS_MAX_TRANSSHIPMENT
  );
  public static String CALCULATED_RATE = 'CalculateRate';
  public static String STR_N = 'N';
  public static String STR_Y = 'Y';
  public static String BREAKBULK = 'breakbulk';
  public static String RORO = 'RoRo';
  public static String CONTAINER = 'Container';
  public static String MULTICONTAINER_CARGOTYPE = 'MultiContainerCargoType';
  public static String STR_FF = 'FF';
  public static String STR_HQ = 'HQ';
  public static String STR_USD = 'USD';
  public static String STR_A = 'A';
  public static String STR_E = 'E';
  public static String STR_F = 'F';
  public static final String FINDAROUTEPOST = 'FindARoutePOST';
  public static final MAP<String, String> mapPortSublocation = new Map<String, String>{
    'USPEF' => 'PEFT001',
    'USJAX' => 'JAXT000',
    'USMIA' => 'MIAT001',
    'USGPT' => 'GPTT000',
    'USILM' => 'ILMT001',
    'USCHT' => 'CHTT000'
  };
  public static String STR_NO = 'No';
  public static String STR_YES = 'Yes';
}
